#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
[[layers]]
  name = "colorscheme"
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "SauceCodePro Nerd Font Mono"
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
[[layers]]
  name = "lsp"
  filetypes = [
   "java"
  ]
  [layers.override_cmd]
   java = [
   "java",
   "-Declipse.application=org.eclipse.jdt.ls.core.id1",
   "-Dosgi.bundles.defaultStartLevel=4",
   "-Declipse.product=org.eclipse.jdt.ls.core.product",
   "-Dlog.protocol=true",
   "-Dlog.level=ALL",
   "-noverify",
   "-Xmx1G",
   "-jar",
   "~/.local/share/languageServer/javaLS/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.300.v20210617-0451.jar",
   "-configuration",
   "~/.local/share/languageServer/javaLS/config_linux",
   "-data"
   ]
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true

[[layers]]
  name = 'lang#java'
  java_formatter_jar = '/home/udbhav/.local/share/Google/google-java-format-1.10.0-all-deps.jar'
  java_file_head = [
    '/**',
    ' * @author : `fnamemodify(expand("~"), ":t")`',
    ' * @created : `strftime("%Y-%m-%d")`',
    '**/',
    ''
  ]

